### ISSUE TITLE
no ||

### ISSUE THREAD

**Issue by moopie** [x89/Tea#1]
https://github.com/x89/Tea/blob/master/tea.sh#L17

needs that || bro

**Comment by anlutro** [comment]
Please formulate your bug report better, with better capitalisation, and refrain from stupid language such as "bro".

**Comment by x89** [comment]
Closed.
@anlutro I would kindly ask you to refrain from pedantry, while @moopie may have been being overtly friendly in a highly commercial world I like to think a little leeway can be given here and there. Especially in regards to tea.

**Comment by anlutro** [comment]
No leeway can be given in regards to tea and tea-related things! This is very disappointing behaviour from an open source project and I shall not be using it!!

**Comment by x89** [comment]
I am extremely upset that you feel this way, I am only trying to help those
in need, those in tea need. The `flac` format was created with you in mind!

**Comment by moopie** [comment]
yous bros needs to chillax alls i'm sayin
