### ISSUE TITLE
Socket / service could be useful for this.

### ISSUE THREAD

**Issue by x89** [x89/Tea#10]
Thinking out loud here. I'm aware that a phone app would do just as well - but we are Linux people.

Right so how about a (systemd) socket or service that waits for input on port 33590 (Decimal unicode symbol for Tea in Chinese I think) for a packet saying START NOW. That would mean you could hit a button on your phone and boom - your tea script starts just like that, the very second you add the boiling water.

It's on the to-do list.

    [Unit]
    # http://www.fileformat.info/info/unicode/char/8336/index.htm
    Description=Listens for other devices telling the socket that water is poured
    
    [Socket]
    ListenStream=33590
    Accept=yes
    
    [Install]
    WantedBy=sockets.target

**Comment by Happy0** [comment]
:+1:

**Comment by x89** [comment]
I'm not incredibly familiar with broadcast addressing (as in send a message to .255?) I was thinking more running in on your own computer and pinging your local LAN IP address.

**Comment by Happy0** [comment]
Fair play! :P

**Comment by ajikeshi** [comment]
if you integrate systemd and add network functionality shouldnt the project be renamed tead?

**Comment by x89** [comment]
Well I mean the `nginx` service is just called that on Arch Linux - though I'm not sure about others. I believe things like Apache are renamed to `httpd` on Debian based systems (I could be wrong there).

I guess it would be down to the implementation details, unless there is some standard that says services should follow `/.*d/`, I'm not aware of one though!

**Comment by x89** [comment]
I'm going to assign this to myself, I have other things I should be doing but I want my tea done right.
