### ISSUE TITLE
Tea.sh does not print usage when the --help flag is used.

### ISSUE THREAD

**Issue by Happy0** [x89/Tea#13]
Tea.sh does not print the usage when the --help flag is used.

Steps to reproduce:
1. Run tea.sh using the --help flag.

Expected:
Tea.sh prints the usage.

Actual:
Tea.sh executes as normal, informing you that your tea is ready in 6 minutes.

Log:
[happy0@delta Tea]$ ./tea.sh --help

You are using tea.flac.
Have no fear! None! You will be warned when your tea is ready.
^C
[happy0@delta Tea]$

Revision: 9e928ba90484283f856515cced828d4765996daf

**Comment by anlutro** [comment]
https://github.com/x89/Tea/blob/9e928ba90484283f856515cced828d4765996daf/tea.sh#L19

This removes all arguments (`$1`, `$2` etc.) which means that `$1` is empty later in the script, and `$#` is always 0.

**Comment by moopie** [comment]
I think this is an important feature that should be added as fast as possible

just the fact that it is here for more than a day with no response from the dev is a bad sign.

**Comment by Happy0** [comment]
Indeed. I no longer have confidence in the management of this project.

I think it's time for a fork! Would you like the role of 'deputy product manager', @moopie?

**Comment by x89** [comment]
I will quickly merge the request.

**Comment by anlutro** [comment]
I think this project should be rewritten in Rust. Rust advertises memory safety which is very important, because the script needs to remember to remind the user that their tea is ready.

**Comment by Happy0** [comment]
I think our fork should be rewritten in Haskell. Haskell promotes explicitly typed effects which is very important because reminding the user that their tea is ready is effectful as it plays an audio clip and prints to standard out.

**Comment by anlutro** [comment]
Reminding a user that their tea is ready counts as a side effect. Haskell does not allow it.

**Comment by Happy0** [comment]
This minor issue can be resolved by attaching a thermometer to the CPU which heats up due to the work required to execute the pure functions in tea.sh which can be captured, despite the limitation of Haskell not allowing side effects. We will write the pure functions in a way that predictably heats up the CPU to transmit 'your tea is ready' in morse code.

**Comment by Happy0** [comment]
Invalid? Our fork is more urgent than I thought!

**Comment by x89** [comment]
Watch it you or it's getting tagged wontfix.

**Comment by anlutro** [comment]
Fixed in https://github.com/x89/Tea/commit/44aff899e1b29ed60ce28328ce2d2eeb6eb45471

**Comment by Happy0** [comment]
Thanks @anlutro. Congratulations on your new job as a maintainer for this prestigious project!

**Comment by x89** [comment]
+1, highly committed individual.
