### ISSUE TITLE
Github could use one of those fancy Tea pages to "advertise" the tea script.

### ISSUE THREAD

**Issue by x89** [x89/Tea#14]

**Comment by x89** [comment]
Alternatively the Readme could be massively improved. But those github.io or io.github.whatever pages - the Github pages thing - it can look amazing!

**Comment by anlutro** [comment]
I can do it, eventually.

**Comment by x89** [comment]
I would assign you but I cannot.

**Comment by x89** [comment]
THERE we go.

**Comment by anlutro** [comment]
Good job!

**Comment by x89** [comment]
Thanks, man.

**Comment by anlutro** [comment]
http://x89.github.io/Tea/

You can edit the HTML files in the `gh-pages` branch to add examples and stuff, I'm not doing that bit.

**Comment by x89** [comment]
Impressed with your efficiency.
