### ISSUE TITLE
A progress bar would be incredible.

### ISSUE THREAD

**Issue by x89** [x89/Tea#17]
Should one run `tea` from the command line it would be rather nice to have a visual guide. Much like when downloading a file for example.

**Comment by dunkyp** [comment]
https://gist.github.com/dunkyp/d8b996f19384b5b06f2d

**Comment by dunkyp** [comment]
it is incredible

**Comment by x89** [comment]
Progress bars are!

**Comment by x89** [comment]
https://github.com/x89/Tea/commit/1bc5b901042c609f4706179e3fb0912a1b716563
