### ISSUE TITLE
Reimplement the tea alarm in nodejs

### ISSUE THREAD

**Issue by moopie** [x89/Tea#3]
While what has been accomplished here is very nice, I think the app would be more useful as a web app

Rebuilding it in nodejs gives you many more advantages like:

* Run it as a website
* Run it as a mobile app
* Have a pretty GUI using webkit, something like what github guys did with their nodejs editor
* Webscale
* Nobody knows what a sh file is or how to use it

**Comment by Happy0** [comment]
:+1:
